import type { Metadata } from "next";
import localFont from "next/font/local";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit",
  weight: ["400"],
});

const omega = localFont({
  src: [
    {
      path: "../public/fonts/omega.ttf",
      weight: "400",
    },
  ],
  variable: "--omega",
});

export const metadata: Metadata = {
  title: "Moodiez Studios",
  description: "Moodiez Studios generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${omega.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
