import type { Metadata } from "next";
import localFont from "next/font/local";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit",
  weight: ["400"],
});

const omega = localFont({
  src: [
    {
      path: "../public/fonts/omega.ttf",
      weight: "400",
    },
  ],
  variable: "--omega",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${omega.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
